site_name: My Docs
site_url: https://docs.ranevm.com
site_author: Rane Danielsen
site_description: This is a weird amalgamation of notes of different kinds that I've tossed together.

repo_name: mkdocs-material
repo_url: https://github.com/raneydazed/mkdocs-material

edit_uri: edit/main/docs/

theme:
  name: material
  features:
  - content.code.copy
  - content.action.edit
  - content.action.view
  - header.autohide
  - navigation.footer
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - navigation.instant
  - navigation.prune
  - toc.follow
  - search.suggest
  - search.highlight
  - search.share
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference