site_name: Raneys' Docs
site_url: https://www.ranevm.com
site_author: Rane Danielsen
site_description: This is a weird amalgamation of notes of different kinds that I've tossed together.

repo_name: mkdocs-material
repo_url: https://github.com/raney-org/mkdocs-material

edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/solid/chair
    repo: octicons/logo-github-16
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      python: fontawesome/brands/python
      docker: fontawesome/brands/docker
      mermaid: fontawesome/brands/mermaid
      diagrams: fontawesome-solid-diagram-project
      data-tables: fontawesome-solid-table
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - content.code.copy
  - content.code.select
  - content.action.edit
  - content.action.view
  - header.autohide
  - navigation.footer
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - navigation.instant
  - navigation.prune
  - navigation.indexes 
  - toc.follow
  - search.suggest
  - search.highlight
  - search.share
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
#   - meta fuckin dumb!!!
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_file: tags.md
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      # skip_classes:
      #   - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - social:
      cards_font: Roboto
  - table-reader

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - pymdownx.keys
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      pygments_lang_class: true
      auto_title: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/shortcuts.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    PYTHON: python
    DOCKER: docker
    DATATABLES: data-tables
  social:
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/RKWgjDqkhR'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/raneydazed/mkdocs-material'
    name: GitHub
  - icon: fontawesome/solid/paper-plane
    link: mailto:support@raneydazed.com
    name: Email
  - icon: fontawesome/brands/linkedin
    link: 'https://www.linkedin.com/in/raneydazed'

  analytics:
    provider: google
    property: G-E76LZ0DT3L
    feedback:
      title: Was this page helpful AF?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful AF
          data: 1
          note: >-
            Thanks for your feedback sucker!!
        - icon: material/emoticon-sad-outline
          name: This page could be improved bub. Like a lot
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2023 Rane Danielsen -
  <a href="#__consent">Change cookie settings</a>

nav:
  - Home: index.md
  - School:
    - school/README.md
    - Informal Logic:
        - General Notes: school/informal-logic/notes.md
        - Book Excerpts: school/informal-logic/book-excerpts.md
        - Learning Activity:
          - Week-3: school/informal-logic/learning-activity/week-3.md
    - Fundamentals of Programming Languages:
        - General Notes: school/programming-languages/notes.md
        - Python:
          - Python: school/programming-languages/python/python-overview.md
          - Variables and Expressions: school/programming-languages/python/variables-expressions.md
  - Tags: tags.md
  - Docker:
    - code/README.md
    - Wiki JS: code/wiki-js.md
    - Audiobookshelf: code/audiobookshelf.md
    - Pihole + Unbound: code/pihole.md
    - YTDL: code/ytdl.md
  - Tests:
      - Mermaid: code/mermaid-test.md
      - Data Tables: code/datatables.md
