name: ci 
on:
  push:
    branches:
      - master 
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

    - name: Checkout Contributors
      uses: actions/checkout@v3

    - name: Add Contributors
      uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'Raney-org/mkdocs-material'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{ secrets.PAC_TOKEN }}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'

  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false && github.event_name != 'pull_request'
    outputs:
      url: ${{ steps.cloudflare.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install Dependencies
      #   uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      #     version: 1.0

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Upgrade PIP
        run: pip install --upgrade pip

      - name: Install wheel
        run: pip install wheel

      - name: Install Cairosvg
        run: pip install pillow cairosvg

      - name: Install Table Reader Plugin
        run: pip install mkdocs-table-reader-plugin

      - name: Install openpyxl
        run: pip install openpyxl

      - name: Install glightbox??
        run: pip install mkdocs-glightbox

      # - name: Install lightgallery
      #   run: pip install lightgallery

      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Mkdocs Material
        run: pip install mkdocs-material

      - name: Build mkdocs
        run: mkdocs build

      - name: Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mkdocs-material
          directory: site
          gitHubToken: ${{ secrets.PAC_TOKEN }}

  webhook:
    name: 'webhook'
    runs-on: self-hosted
    needs: [build]
    if: always() && github.event_name != 'pull_request'
    steps:
      - name: Workflow-Conclusion Actions
        uses: technote-space/workflow-conclusion-action@v3

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "URL: ${{ needs.build.outputs.url }}"
          status: ${{ env.WORKFLOW_CONCLUSION }}