name: Close inactive issues
on:
  schedule:
    - cron: "30 8 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-issue-stale: 20
          days-before-issue-close: 1
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 20 days with no activity. Leave a comment to avoid closing this issue in 1 day."
          close-issue-message: "This issue was closed because it has been inactive for 1 day since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}